# Substitution variables used through the codebase
substitutions:
  icon_font: mdi_icons_40
  text_font: nunito_24
  text_color: white
  bg_color: black
  button_on_color: "ep_orange"
  #button_off_color: "very_dark_gray"
  button_off_color: "sky_blue"
  icon_on_color: "yellow"
  #icon_off_color: "gray"
  icon_off_color: "white"
  label_on_color: "red"
  #label_off_color: "gray"
  label_off_color: "white"
  button_text_color: "white"
  button_height_single: '109px'
  button_height_double: '228px'
  button_width: '150px'
  touchscreen_idle_timeout: "30s"
  touchscreen_daytime_brightness: "100%"
  touchscreen_nighttime_brightness: "50%"

  # Boot screen configuration
  boot_screen_delay: 60s

  # LCD backlight modes - Code in backlight.yaml
  # Day mode is set to Sunrise
  # Evening mode is set to sunset
  # Set Night mode  at Mightnight here
  screen_night_hour: '0'
  screen_night_minute: '0'

  # Screen Size
  screen_height: '480'
  screen_width: '480'
  byte_order: big_endian  

esphome:
  name: "display01"
  friendly_name: "Display 01"
  comment: "ospreypi-esp32-s3 480px * 480px Smart Screen"
  includes:
    - <sstream>
    - <algorithm>
  on_boot:
    - priority: 400
      then:
        - script.execute: update_loading_page

logger:
  level: debug

# Time update script - This is run once per second. Use it to update any time related labels.


packages:
  # Generic configuration for ESP32 screens
  # SDL has no Wi-Fi
  wifi: !include esphome-modular-lvgl-buttons/common/wifi.yaml
  # Home Assistant Extras
  ha_control: !include esphome-modular-lvgl-buttons/common/ha_control.yaml
  # Enable OTA updates with a status screen
  ota_screen: !include esphome-modular-lvgl-buttons/common/ota.yaml
  # All the colors
  colors: !include esphome-modular-lvgl-buttons/common/color.yaml
  # Some nice basic fonts
  fonts: !include esphome-modular-lvgl-buttons/common/fonts.yaml
  # 1000s of glyphs
  glyphs: !include esphome-modular-lvgl-buttons/common/mdi_glyph_substitutions.yaml
  # Weather icons for screensaver
  weather_icons: !include esphome-modular-lvgl-buttons/common/weather_icons.yaml
  # Some basic sensors
  sensors: !include esphome-modular-lvgl-buttons/sensors/sensors_base.yaml
  # Styles + Themes
  theme_style: !include esphome-modular-lvgl-buttons/common/theme_style.yaml
  # Include if your touch screen has a backlight. Also sets the time from HA
  backlight: !include esphome-modular-lvgl-buttons/common/backlignt_time.yaml

  # Harware description file
  hardware: !include esphome-modular-lvgl-buttons/hardware/ospreypi-esp32-s3-48x48.yaml
  
  # Basic boot screen with ESPHome logo and device diagnostic info
  loading_screen: !include esphome-modular-lvgl-buttons/pages/loading_480px.yaml
  info_screen: !include esphome-modular-lvgl-buttons/pages/info.yaml

  # Screensaver
  screensaver: !include esphome-modular-lvgl-buttons/pages/screensaver.yaml

  # This section will Update button state and relay state from Home Assistant
  # Any button that has real time updates needs a section here


  # Button Type definitions
  # └──────────────┴──────────────┴──────────────┘
  # │  Button Layout (480x480 screen - 3 columns)│
  # ├──────────────┬──────────────┬──────────────┤
  # │   Button 1   │   Button 4   │   Button 7   │
  # │   Bedroom    │   WLED Bed   │     WLED     │
  # │   (double)   │   (double)   │   (double)   │
  # ├──────────────┼──────────────┼──────────────┤
  # │   (Empty)    │   Button 5   │   (Empty)    │
  # │              │  Play/Pause  │              │
  # │   (single)   │   (single)   │   (single)   │
  # ├──────────────┼──────────────┼──────────────┤
  # │   Button 3   │   (Empty)    │   Button 9   │
  # │    Pantry    │              │     Exit     │
  # │   (single)   │   (single)   │   (single)   │
  # └──────────────┴──────────────┴──────────────┘

# light.bedroom_lights
# switch.fun_group
# light.pantry_light
# switch.media_play_pause
# switch.call_sleep_script
# switch.call_exit_script
#
#
#



  # Button 1 - Remote switch controller (controls HA switch, doesn't create new entity)
  button_1_state: !include
    file: esphome-modular-lvgl-buttons/sensors/switch_or_light_button_state.yaml
    vars:
      uid: button_1
      entity_id: "light.bedroom_lights"

  # Button 2 - Remote switch controller (controls HA switch, doesn't create new entity)
  button_2_state: !include
    file: esphome-modular-lvgl-buttons/sensors/switch_or_light_button_state.yaml
    vars:
      uid: button_2
      entity_id: "switch.fun_group"

  # Button 3 - Remote switch controller (controls HA switch, doesn't create new entity)
  button_3_state: !include
    file: esphome-modular-lvgl-buttons/sensors/switch_or_light_button_state.yaml
    vars:
      uid: button_3
      entity_id: "light.pantry_light"

  # Button 4.5 - Remote switch controller (controls HA switch, doesn't create new entity)
  button_4_5_state: !include
    file: esphome-modular-lvgl-buttons/sensors/script_state.yaml
    vars:
      uid: button_4_5
      state_entity_id: "light.wled_new" # Changed from script to light entity for state tracking

  # Button 5 - Remote switch controller (controls HA switch, doesn't create new entity)
  button_5_state: !include
    file: esphome-modular-lvgl-buttons/sensors/play_pause_button_state.yaml
    vars:
      uid: button_5
      entity_id: "switch.media_play_pause"

  # Button 6 - Remote switch controller (controls HA switch, doesn't create new entity)
  button_6_state: !include
    file: esphome-modular-lvgl-buttons/sensors/switch_or_light_button_state.yaml
    vars:
      uid: button_6
      entity_id: "switch.call_sleep_script"

  # Button 7 - State (Main Page)
  button_7_state: !include
    file: esphome-modular-lvgl-buttons/sensors/dimmer_light_state.yaml
    vars:
      uid: wled_new
      entity_id: "light.wled_new"
      
  # Button 7 - Detail Page
  button_7_page: !include
    file: esphome-modular-lvgl-buttons/pages/light_color.yaml
    vars:
      widget_name: wled_new
      light_entity: "light.wled_new"



  # Button 9 - Remote switch controller (controls HA switch, doesn't create new entity)
  button_9_state: !include
    file: esphome-modular-lvgl-buttons/sensors/switch_or_light_button_state.yaml
    vars:
      uid: button_9
      entity_id: "switch.call_exit_script"
# -------------------------------------------------------------------------
# LVGL pages and buttons
# -------------------------------------------------------------------------
lvgl:
# Main Page
  pages:
    - id: main_page
      layout:
        type: flex
        flex_flow: COLUMN_WRAP
      width: 100%
      styles: page_style
      #bg_color: black
      bg_image_src: screensaver_bg_image3
      bg_opa: cover
      <<: !include
        file: esphome-modular-lvgl-buttons/widgets/swipe_navigation.yaml
      widgets:

        # Button 1 - Standard light button with state updates
        - button: !include
            file: esphome-modular-lvgl-buttons/buttons/light_button.yaml
            vars:
              uid: button_1
              height: $button_height_double
              text: bedroom
              icon: $mdi_lightbulb
              entity_id: "light.bedroom_lights" 

        # Button 2 - Standard light button with state updates
        - button: !include
            file: esphome-modular-lvgl-buttons/buttons/switch_button.yaml
            vars:
              uid: button_2
              height: $button_height_single
              text: fun
              icon: $mdi_fan
              entity_id: "switch.fun_group"

        # Button 3 - Standard light button with state updates
        - button: !include
            file: esphome-modular-lvgl-buttons/buttons/light_button.yaml
            vars:
              uid: button_3
              height: $button_height_single
              text: pantry light
              icon: $mdi_lightbulb
              entity_id: "light.pantry_light"

        # Button 4.5 - Standard light button with state updates
        - button: !include
            file: esphome-modular-lvgl-buttons/buttons/script_button.yaml
            vars:
              uid: button_4_5
              height: $button_height_single
              text: wled
              icon: $mdi_string_lights
              entity_id: "script.wled_light_togle_animated"

        # Button 4 - Empty button moves the buttons below it down one
        - button: !include
            file: esphome-modular-lvgl-buttons/buttons/transparent_empty_button.yaml
            vars:
              uid: empty_4
              height: $button_height_single

        # Button 5 - Standard light button with state updates
        - button: !include
            file: esphome-modular-lvgl-buttons/buttons/fullscreen_icon_button.yaml
            vars:
              uid: button_5
              height: $button_height_single
              icon: $mdi_play_pause
              font: mdi_icons_80
              entity_id: "switch.media_play_pause"

        # Button 6 - Standard light button with state updates
        - button: !include
            file: esphome-modular-lvgl-buttons/buttons/switch_button.yaml
            vars:
              uid: button_6
              height: $button_height_single
              text: sleep
              icon: $mdi_weather_night
              entity_id: "switch.call_sleep_script"

        # Button 7 - Dimming light button (wled_new)
        - button: !include
            file: esphome-modular-lvgl-buttons/buttons/dimmer_light_button.yaml
            vars:
              uid: wled_new
              height: $button_height_double
              text: wled bed
              icon: $mdi_string_lights
              entity_id: "light.wled_new"

        # Button 8 - Empty button moves the buttons below it down one
        - button: !include
            file: esphome-modular-lvgl-buttons/buttons/transparent_empty_button.yaml
            vars:
              uid: empty_8
              height: $button_height_single

        # Button 9 - Standard light button with state updates
        - button: !include
            file: esphome-modular-lvgl-buttons/buttons/switch_button.yaml
            vars:
              uid: button_9
              height: $button_height_single
              text: exit
              icon: $mdi_location_exit
              entity_id: "switch.call_exit_script"
# -------------------------------------------------------------------------
# Fonts and graphics
# -------------------------------------------------------------------------

# I you want to use other MDI icons add them to the list here
font:
  # http://materialdesignicons.com/cdn/7.4.47/
  - file: 'https://github.com/Templarian/MaterialDesign-Webfont/raw/v7.4.47/fonts/materialdesignicons-webfont.ttf'
    id: mdi_icons_40
    size: 40
    bpp: 8
    glyphs: [
      $mdi_lightbulb,  # mdi-lightbulb
      $mdi_ceiling_light,  # mdi-ceiling-light
      $mdi_lamp,  # mdi-lamp
      $mdi_floor_lamp,  # mdi-floor-lamp
      $mdi_string_lights,  # mdi-string-lights
      $mdi_track_light,  # mdi-track-light
      $mdi_bulkhead_light,  # mdi-bulkhead_light
      $mdi_led_strip,  # mdi-led-strip
      $mdi_coach_lamp,  # mdi-coach-lamp
      $mdi_ceiling_fan_light,  # mdi-ceiling-fan-light
      $mdi_bed,  # mdi-bed
      $mdi_white_balance_sunny,  # mdi-white-balance-sunny
      $mdi_brightness_6,  # mdi-brightness-6
      $mdi_home,  # mdi-home (for color picker back button)
      $mdi_weather_night,  # mdi-weather-night (for good night scene)
      $mdi_movie,  # mdi-movie (for movie scene)
      $mdi_sofa,  # mdi-sofa (for relax scene)
      $mdi_silverware_fork_knife,  # mdi-silverware-fork-knife (for dinner scene)
      $mdi_play_pause,  # mdi-play-pause (for play/pause scene)
      $mdi_play,        # mdi-play
      $mdi_pause,       # mdi-pause
      $mdi_location_exit,  # mdi-location-exit (for exit scene)
      $mdi_fan,         # mdi-fun
    ]
  - file: 'https://github.com/Templarian/MaterialDesign-Webfont/raw/v7.4.47/fonts/materialdesignicons-webfont.ttf'
    id: mdi_icons_80
    size: 80
    bpp: 8
    glyphs: [
      $mdi_play_pause,  # mdi-play-pause (for play/pause scene)
      $mdi_play,        # mdi-play
      $mdi_pause,       # mdi-pause
    ]

# Images (must be in main YAML for global visibility)
image:
  - file: esphome-modular-lvgl-buttons/assets/images/light/lightbulb.png
    id: lightbulb_image
    resize: 100x100
    type: RGB565
    transparency: alpha_channel
  - file: esphome-modular-lvgl-buttons/assets/bg/bg.jpg
    id: screensaver_bg_image
    type: RGB565
  - file: esphome-modular-lvgl-buttons/assets/bg/ota.jpeg
    id: screensaver_bg_image2
    type: RGB565
  - file: esphome-modular-lvgl-buttons/assets/bg/bg1.jpg
    id: screensaver_bg_image3
    type: RGB565
  - file: esphome-modular-lvgl-buttons/assets/bg/sync4.jpg
    id: sync4
    type: RGB565